import "./globals.css";
import type { Metadata } from "next";

import { Prompt } from "next/font/google";
const prompt = Prompt({ subsets: ["latin"], weight: ['400','500', '600', '700'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: 
  Readonly<{ children: React.ReactNode }>) 
  {return (
    <html lang="PT-BR">
      <body className={prompt.className}>
        {children}
      </body>
    </html>
  );
}
